export enum RegisterStatus{
  PRE_REGISTER = 'PRE_REGISTER',
  OPR_REJECTED = 'OPR_REJECTED',
  OPR_ACCEPTED = 'OPR_ACCEPTED',
  ADDRESS_CONFIRMED = 'ADDRESS_CONFIRMED',
  PAYMENT_DONE = 'PAYMENT_DONE',
  HOTEL_ADDRESS_CONFIRMED = 'HOTEL_ADDRESS_CONFIRMED',
  CANCELED = 'CANCELED',
}
